<?php
use PhpCupcakes\Config\ConfigVars;




?>
<form id="browseForm" action="<?= ConfigVars::getSiteUrl().$_SERVER['REQUEST_URI'] ?>" method="get">
    <label for="browseColumn">Order by:</label>

    <select id="browseColumn" name="browseColumn">
        <option value="">Select a column</option>
        <?php
        foreach ($classNamespace::$propertyMetadata as $columnName => $metadata) {
            if ($metadata['sortbyAsc'] == true) {
            ?>
            <option value="<?= $columnName ?>-ASC"><?= $metadata['userFriendlySortAsc'] ?></option>
            <?php
            }
            if ($metadata['sortbyDesc'] == true) {
            ?>
            <option value="<?= $columnName ?>-DESC"><?= $metadata['userFriendlySortDesc'] ?></option>
            <?php
            }
        }

        ?>
    </select>
    <input type="submit" name="browse" value="go" />
</form>

<form id="itemsPerPage" action="<?= ConfigVars::getSiteUrl().$_SERVER['REQUEST_URI'] ?>" method="get">
    <label for="itemsPerPage">Items per Page:</label>

    <select id="itemsPerPage" name="items_per_page">
    <option value="5">5</option>
    <option value="10" selected>10</option>
    <option value="15">15</option>
    <option value="25">25</option>
    <option value="50">50</option>
    <option value="100">100</option>
    <option value="250">250</option>

    </select>
    <input type="submit" name="itemsPerPage" value="go" />
</form>