<?php
require_once $_SERVER["DOCUMENT_ROOT"] . "/Framework/autoload.php"; /*linkhere*/
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;
use PhpCupcakes\Config\Analytics;
?>
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= Analytics::Google() ?>
    <title>PHPCupcakes Example</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere--> 
</head>
<body>
    
    <div class="container">
<header>
    <?php
    echo LoadHtml::loadInclude("header");
    ?>
<div class="search bg-info">
    <?php echo LoadHtml::loadInclude("searchform"); ?>
</div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude("nav") ?>
   
<?php
use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();
?></nav>


<div class="mainparent">
    <main>
    <h4>404: Page Not Found.</h4>
    <h5>If you feel you have reached this in error, please <a href="mailto:aemegi@icloud.com">contact webmaster</a>. Please include the URL.</h5> 
</main>
</div>
</div>
</body>
</html>