<?php
    require_once '../../Framework/autoload.php';       /*linkhere*/
use PhpCupcakes\Helpers\FormHelper;
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;
use PhpCupcakes\Models\MyObject;

?>
<!DOCTYPE html>
<html>
<head>
    <title>My Objects</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere--> 
</head>
<body>
    <div class="container">
    <header>
        <?php 
        $h1 = 'Add to My Objects';
        echo LoadHtml::loadInclude('header', ['h1' => $h1]);
        ?>
    <div class="search bg-info"><?php LoadHtml::loadInclude('searchform'); ?></div>
</header>
    <nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude('nav'); ?>
<?php 

use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();


?></nav>
    <div class="mainparent">
<main>
    <?php
    require_once ConfigVars::getFrameworkSrc().'/EditMode/auth.inc.php';       /*linkhere*/

    // Render the form open tag
    echo FormHelper::renderFormOpen('added', 'post', ['class' => 'form-horizontal']);

    // Render form fields

    foreach (MyObject::$propertyMetadata as $columnName => $metadata) {
        $renderFormField = 'render' . $metadata['formfield'];
        $placeholder = $metadata['placeholder'];
        echo FormHelper::$renderFormField($columnName, '', ['class' => 'form-control', 'placeholder'=> $placeholder]);
    }
    // Render the submit button
    echo FormHelper::renderSubmit('Submit', 'submit', ['class' => 'btn btn-primary']);

    // Render the form close tag
    echo FormHelper::renderFormClose();
    ?>
</main></div>
</div></body>
</html>