<?php
    require_once '../../Framework/autoload.php';       /*linkhere*/
use PhpCupcakes\Helpers\FormHelper;
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;

?>
<!DOCTYPE html>
<html>
<head>
    <title>My Objects</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere--> 
</head>
<body>
    <div class="container">
    <header>
        <?php 
        $h1 = 'Add to My Objects';
        echo LoadHtml::loadInclude('header', ['h1' => $h1]);
        ?>
    <div class="search bg-info"><?php LoadHtml::loadInclude('searchform'); ?></div>
</header>
    <nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude('nav'); ?>
<?php 

use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();


?></nav>
    <div class="mainparent">
<main>
    <?php
    require_once ConfigVars::getFrameworkSrc().'/EditMode/auth.inc.php';       /*linkhere*/

    // Render the form open tag
    $formOpen = FormHelper::renderFormOpen('added', 'post', ['class' => 'form-horizontal']);

    // Render form fields
    $nameInput = FormHelper::renderInput('text', 'name', '', ['class' => 'form-control', 'placeholder'=> 'choose a name']);
    $descriptionTextarea = FormHelper::renderTextarea('description', '', ['class' => 'form-control', 'placeholder'=> 'write a description']);

    // Render the submit button
    $submitButton = FormHelper::renderSubmit('Submit', 'submit', ['class' => 'btn btn-primary']);

    // Render the form close tag
    $formClose = FormHelper::renderFormClose();

    // Combine all the form elements
    $form = $formOpen . $nameInput . $descriptionTextarea . $submitButton . $formClose;
    echo $form;
    ?>
</main></div>
</div></body>
</html>