<?php
    require_once '../../Framework/autoload.php';       /*linkhere*/
use PhpCupcakes\Helpers\FormHelper;
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Models\MyObject;
use PhpCupcakes\Config\ConfigVars;
//use PhpCupcakes\Helpers\UrlHelper;

?>
<!DOCTYPE html>
<html lang="en">
 <head>
 <meta name="robots" content="noindex, nofollow" />
  <meta charset="UTF-8">
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PhpCupcakeShop: Edit an Object</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere-->  
</head>
<body>
    <div class="container">
        <header>
            <?= LoadHtml::loadInclude('header'); ?>
        <div class="search bg-info"><?= LoadHtml::loadInclude('searchform'); ?></div>
</header>
    <nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude('nav'); ?>
<?php 

use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();


?></nav>
    <div class="mainparent">
<main>
    <?php
    require_once ConfigVars::getFrameworkSrc().'/EditMode/auth.inc.php';       /*linkhere*/

    $object = MyObject::find($_GET['id']);
    ob_start();
    // Render the form open tag
    echo FormHelper::renderFormOpen(ConfigVars::getSiteUrl().'/update/MyObject/'.$object->id, 'post', ['class' => 'form-horizontal']);       /*linkhere*/

    // Render form fields
    echo FormHelper::renderHidden('id', $_GET['id']);
    echo FormHelper::renderInput('text', 'objects-name', htmlspecialchars($object->name), ['class' => 'form-control']);
    echo FormHelper::renderTextarea('objects-description', htmlspecialchars($object->description), ['class' => 'form-control']);

    //include the CSRF token
    ?><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><?php
    // Render the submit button
    echo FormHelper::renderSubmit('Submit', 'submit', ['class' => 'btn btn-primary']);

    // Render the form close tag
    echo FormHelper::renderFormClose();

    $displayObject = ob_get_clean();
    echo $displayObject;
    ?>
    <a href="#" onclick="history.back()">back</a>
</main></div>
</div></body>
</html>