<?php
require_once "../../Framework/autoload.php"; /*linkhere*/
use PhpCupcakes\Models\MyObject;
use PhpCupcakes\Helpers\PaginationHelper;
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;
use PhpCupcakes\DAL\VanillaCupcakeDAL;
?>
    <!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Objects</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere-->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" />
</head>
<body>
    <div class="container">
        <header>
            <?php
            $h1 = "My Objects";
            echo LoadHtml::loadInclude("header", ["h1" => $h1]);
            ?>
        <div class="search bg-info"><?= LoadHtml::loadInclude(
            "searchform"
        ) ?></div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude("nav") ?>
<?php
use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();
?></nav>
    <div class="mainparent">
    <main>
        <?php $includeVariables = [
            "classNamespace" => "PhpCupcakes\\Models\\MyObject",
        ]; ?>
    <div class="search bg-info"><?= LoadHtml::loadInclude(
        "columnorder",
        $includeVariables
    ) ?></div>

    <?php // Get the current page and items per page from the URL parameters


    list($currentPage, $itemsPerPage) = PaginationHelper::getPaginationParams();
    $table = MyObject::getTableName();
    if (!VanillaCupcakeDAL::tableExists($table)) {
        echo "Sorry no results to display. Add an item from the link above.";
    } else {
        $objects = MyObject::findAllPaginateSorted($currentPage, $itemsPerPage); // Display the objects
        foreach ($objects as $object) {
            ob_start(); ?>
        <div style="display: flex; flex-direction: row; padding: 20px;">
        <div class="quickpadding">Name: <a href="<?= ConfigVars::getSiteUrl() ?>/view/MyObject/<?= $object->id ?>"><?= htmlspecialchars(
    $object->name
) ?></a></div>   <!--linkhere--> 
        <div class="quickpadding">Description: <?= htmlspecialchars(
            $object->description
        ) ?></div>
        <?php echo LoadHtml::loadComponent("editmode/displayEdit", [
            "id" => $object->id,
            "type" => "MyObject",
        ]); ?> 
        </div>
        <?php
        $displayObject = ob_get_clean();
        echo $displayObject;

        } // Display the pagination links
        $totalObjects = MyObject::getTotalofAll();
        PaginationHelper::displayPaginationLinks(
            $totalObjects,
            $currentPage,
            $itemsPerPage
        );
    }
    ?>

</main>
</div>
</div>
</body>
</html>