<?php
    require_once '../../Framework/autoload.php';       /*linkhere*/
    use PhpCupcakes\Models\MyObject;
    use PhpCupcakes\Helpers\PaginationHelper;
    use PhpCupcakes\Helpers\LoadHtml;
    //use PhpCupcakes\Helpers\UrlHelper;
    //use PhpCupcakes\Helpers\IconHelper;
    use PhpCupcakes\Config\ConfigVars;
    ?>
    <!DOCTYPE html>
<html>
<head>
    <title>My Objects</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere-->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" />
</head>
<body>
    <div class="container">
        <header>
            <?php 
            $h1 = 'My Objects';
            echo LoadHtml::loadInclude('header', ['h1' => $h1]);
            ?>
        <div class="search bg-info"><?= LoadHtml::loadInclude('searchform'); ?></div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude('nav'); ?>
<?php 

use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();


?></nav>
    <div class="mainparent">
    <main>

    <?php

    // Get the current page and items per page from the URL parameters
    list($currentPage, $itemsPerPage) = PaginationHelper::getPaginationParams();
    
    $objects = MyObject::findAllPaginated($currentPage, $itemsPerPage);

    
    // Display the objects
    foreach ($objects as $object) {
        ob_start();
        ?>
        <div style="display: flex; flex-direction: row; padding: 20px;">
        <div class="quickpadding">Name: <a href="<?= ConfigVars::getSiteUrl() ?>/MyObject/view/<?= $object->id ?>"><?= $object->name ?></a></div>   <!--linkhere--> 
        <div class="quickpadding">Description: <?= $object->description ?></div>
        <?php
        echo LoadHtml::loadComponent('editmode/displayEdit', ['id' => $object->id, 'type' => 'MyObject']);
        ?> 
        </div>
        <?php
        $displayObject = ob_get_clean();
        echo $displayObject;
    }
    
    // Display the pagination links
    $totalObjects = MyObject::getTotalofAll();
    PaginationHelper::displayPaginationLinks($totalObjects, $currentPage, $itemsPerPage);
    ?>

</main>
</div>
</div>
</body>
</html>