<?php
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;
use PhpCupcakes\Config\Analytics;
?>
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= Analytics::Google() ?>
    <title>PHPCupcakes Example</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere--> 
</head>
<body>
    
    <div class="container">
<header>
    <?php
    echo LoadHtml::loadInclude("header");
    ?>
<div class="search bg-info">
    <?php echo LoadHtml::loadInclude("searchform"); ?>
</div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude("nav") ?>
   
<?php
use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();
?></nav>


<div class="mainparent">
    <main>
   <h4>To begin, go into edit mode and add a(n) <?= $objectName ?> object.</h4>
    <?php 
    if (isset($_SESSION['access_token'])) {
    echo "Welcome, " . $_SESSION['username'] . "!";
    echo "Your user id is ". $_SESSION['user_id'];
    }
    ?>    

    <?php

    ?>
</main>
</div>
</div>
</body>
</html>