<?php

use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;
use PhpCupcakes\Config\Analytics;

use Objects\Relationships\MyObjectMyCategory;


?>
    <!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
 <meta name="robots" content="noindex, nofollow" />
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?= Analytics::Google() ?>
  <title><?= ConfigVars::myAppName() ?> - Admin Portal</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere-->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" />
</head>
<body>
    <div class="container">
        <header>
            <?php
            echo LoadHtml::loadInclude("header");
            ?>
        <div class="search bg-info"><?= LoadHtml::loadInclude("searchform") ?></div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude("nav") ?>
<?php
use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();
?></nav>
    <div class="mainparent">
    <main>
    <?php 





$objectCategories = MyObjectMyCategory::getRelatedMyCategories(1);

foreach ($objectCategories as $category) {
    print_r($category);
}


/*View objects by category

$categoryObjects = MyObjectMyCategory::getRelatedMyObjects(1);

foreach ($categoryObjects as $object) {
    print_r($object);
}

*/
/* Added
    $MyObjectID = 1;
    $MyCategoryID = 1;

    
    $tableRow = new MyObjectMyCategory();
    foreach (MyObjectMyCategory::$propertyMetadata as $columnName => $metadata) {
        $tableName = MyObjectMyCategory::getTableName();
        if ($columnName == "id") {
        } else {
            $tableRow->$columnName = 1;
        }
    }
    $tableRow->save();
    $lastInsertId = $tableRow->id;
    ?>
    <p>tableRow successfully inserted into the database. <?= $lastInsertId ?>">View your object here</a>.</p>    
*/
?>
</main>
</div>
</div>
</body>
</html>
