<?php
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;


?>
<!DOCTYPE html>
<html lang="en">
 <head>
 <meta name="robots" content="noindex, nofollow" />
  <meta charset="UTF-8">
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHPCupcakes Example</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">
</head>
<body>
    
    <div class="container">
        <header>
            <?php
            echo LoadHtml::loadInclude("header");
            ?>
        <div class="search bg-info"><?= LoadHtml::loadInclude("searchform") ?></div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude("nav") ?>
<?php
use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();
?></nav>
<div class="mainparent">
    <main>
    <?php
    require_once ConfigVars::getFrameworkSrc() . "/EditMode/auth.inc.php";
    
    use PhpCupcakes\Helpers\CheckFormToken;

    if (CheckFormToken::checkCSRFToken() == true) {

    $Locations = $routedClassNamespace::find($_GET["id"]);
    //$Locations->id = $_POST["id"];
    foreach ($Locations::$propertyMetadata as $columnName => $metadata) {
        if ($metadata['isForm'] == true) {
        $Locations->$columnName = $_POST[$routedClassNamespace::getTableName()."-".$columnName];

        }
    }

    $Locations->save();
    $lastInsertId = $Locations->id;
    ?>
    <p>Locations successfully inserted into the database. <a href="<?= ConfigVars::getSiteUrl() ?>/admin/<?= $routedClassNamespaceRoot ?>/view/<?= basename($routedClassNamespace) ?>?id=<?= $lastInsertId ?>">View your object here</a>.</p>
    <?php

    }
    ?>
</main>
</div>
</div>
</body>
</html>
