<?php

use PhpCupcakes\Helpers\PaginationHelper;
use PhpCupcakes\Helpers\LoadHtml;
use PhpCupcakes\Config\ConfigVars;
use PhpCupcakes\DAL\VanillaCupcakeDAL;
?>
    <!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="description" content="PHP Cupcake Shop Framework Demo">
 <meta name="keywords" content="PHP, Framework, Demo">
  <meta name="author" content="aemegi">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Objects</title>
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css">   <!--linkhere--> 
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/colors.css">  <!--linkhere-->  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" />
</head>
<body>
    <div class="container">
        <header>
            <?php
            echo LoadHtml::loadInclude("header");
            ?>
        <div class="search bg-info"><?= LoadHtml::loadInclude("searchform") ?></div>
</header>
<nav class="bg-success-light text-dark"><?= LoadHtml::loadInclude("nav") ?>
<?php
use PhpCupcakes\EditMode\EditLink;
echo EditLink::displayEditModeNav();
echo EditLink::displayEditLink();
?></nav>
    <div class="mainparent">
    <main>
        <?php $includeVariables = [
            "classNamespace" => $routedClassNamespace,
        ]; ?>
    <div class="search bg-info"><?= LoadHtml::loadInclude("columnorder", $includeVariables) ?></div>

    <?php 


    list($currentPage, $itemsPerPage) = PaginationHelper::getPaginationParams();
    $table = $routedClassNamespace::getTableName();
    if (!VanillaCupcakeDAL::tableExists($table)) {
        echo "Sorry no results to display. Add an item from the link above.";
    } else {
        $objects = $routedClassNamespace::findAllPaginateSorted($currentPage, $itemsPerPage); 
        foreach ($objects as $object) {
            ob_start();
            ?>
            <div style="display: flex; flex-direction: row; padding: 20px;">
            <?php
            foreach ($object::$propertyMetadata as $columnName => $metadata) {
                if ($metadata['display'] == true) {
                ?>
            <div class="quickpadding"><?= $metadata['userFriendlyName'] ?>:&nbsp;
                <?php
                    if (!isset($metadata['isLink']) || $metadata['isLink'] == false) {
                        ?>
                <?= htmlspecialchars($object->$columnName) ?>
                <?php
                    } else { 
                        ?>
                        <a href="<?= ConfigVars::getSiteUrl() ?>/admin/<?= $routedClassNamespaceRoot ?>/view/<?= basename($routedClassNamespace) ?>?id=<?= $object->id ?>"><?= htmlspecialchars($object->$columnName) ?></a>
                        <?php
                    }
                    ?>
                    </div> 
            <?php
                }
            }
            ?>
            <?php 
            
            $namespaceParts = explode('\\', $routedClassNamespace);
            $firstParameter = $namespaceParts[0];
            $thirdParameter = $namespaceParts[2];
            
            
            
            
            echo LoadHtml::loadComponent("editmode/displayEdit", [
                "id" => $object->id,
                "routedClass" => $thirdParameter,
                "routedClassNamespaceRoot" => $routedClassNamespaceRoot,
            ]); ?> 
            </div>
            <?php
            $displayObject = ob_get_clean();
            echo $displayObject;

        } // Display the pagination links
        $totalObjects = $routedClassNamespace::getTotalofAll();
        PaginationHelper::displayPaginationLinks(
            $totalObjects,
            $currentPage,
            $itemsPerPage
        );
    }
    ?>

</main>
</div>
</div>
</body>
</html>
