<?php
require_once $_SERVER['DOCUMENT_ROOT'].'/Framework/autoload.php';

use prettylinktree\Models\LinkTree;
use PhpCupcakes\Config\ConfigVars;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= ConfigVars::myAppName() ?> - prettylinktree</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="/vendor/linktree/assets/css/main.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>    
    <link rel="stylesheet" href="<?= ConfigVars::getWWW() ?>/assets/css/styles.css"> 
    <style>
.container {
  height: 100%;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}
.fab {
    text-decoration: none;
}
.tooltip {
  position: relative;
  display: inline-block;
  border-bottom: 1px dotted black;
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0;

  /* Position the tooltip */
  position: absolute;
  z-index: 1;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
}
ul {
    display: flex;
    flex-direction: row;
    
  list-style-type: none; /* Remove bullets */
}
.quickpadding {
  padding: 20px;
}



        /* Existing CSS styles */
    </style>
</head>
<body>
    <div class="container">
        <div class="profile-info">
            <img src="../../www/assets/img/logo.png" width="300" style="border-radius: 50%;" alt="Profile Picture">
            <h1>PhpCupcakeShop prettylinktree</h1>
            <p>A Simple CMS linktree plugin for PhpCupcakeShop. To begin click edit mode below.</p>
        </div> 

          <?php include "linktree.phtml"; ?>
     

        <div class="footer">
            <p>&copy; <?= date('Y') ?> PhpCupcakeShop</p>
            <p><?php include 'vendor/linktree/components/nav.phtml'; ?></p>
        </div>
    </div>
   </div>
   
</body>
</html>